### ISSUE TITLE
Tmux starting function should parse a project specific config file

### ISSUE THREAD

**Issue by jcmorrow** [gabebw/dotfiles#40]
This isn't actually an issue with your dotfiles, I just wanted to share an idea (and also have you tell me if something already does this). I have a few projects where my tmux setup involves project specific windows (an ngrok window for example). It would be great to include a file in the project's root directory like:

    code: vim
    server: foreman start
    console: rails c
    ngrok: ngrok http 3000

and have the script parse it as:

1. Each line is a new window
2. Key is the name of the window
3. Value is the command to run in that window on startup

Does something already do this? If not, is it a terrible idea?

**Comment by gabebw** [comment]
Is [Teamocil](https://github.com/remiprev/teamocil#readme) exactly what you want?

**Comment by adarsh** [comment]
I like [tmuxinator][1] for this purpose.

[Config files are in YAML][2]:

```yaml
name: project_name
root: /Users/adarsh/devproject_name

windows:
  - code:
      layout: 9f82,255x64,0,0{173x64,0,0,4,81x64,174,0,5}
      panes:
        - vim
        - git checkout master
  - server: foreman start
  - logs: tail -f log/development.log

```

then just `mux project_name` to spin up a new session or connect to the existing one.

[1]: https://github.com/tmuxinator/tmuxinator
[2]: https://github.com/adarsh/dotfiles/blob/master/tmuxinator/rubytogether.yml
